config/routes.rb
Kevinstone::Application.routes.draw do

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/gallery(/:page)', to: 'photos#gallery', as: :gallery

  resources :articles
  resources :videos
  resources :photos
  resources :dynamic_contents
  resources :events
  resources :pages, except: [:show]

  get '/contact-us', to: 'contact_us/contacts#new', as: :contact_us
  post '/contact', to: 'contact_us/contacts#new', as: :contact_kevin
  match 'blog', to: 'articles#index', as: :blog
  match ':id', to: 'pages#show', as: :page

end

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Permalink</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.permalink %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', root_path %></li>
  <li class="active"><%= @page.name %></li>
</ol>
<h3><%= @page.name %></h3>
<% if @page.page_image.url %>
<%= image_tag @page.page_image.url, class: 'img-float-right img-responsive' %>
<% end %>
<%= @page.content.html_safe %>