config/routes.rb
Kevinstone::Application.routes.draw do

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/gallery(/:page)', to: 'photos#gallery', as: :gallery

  resources :articles
  resources :videos
  resources :photos
  resources :dynamic_contents
  resources :events
  resources :pages, except: [:show]

  get '/contact-us', to: 'contact_us/contacts#new', as: :contact_us
  post '/contact', to: 'contact_us/contacts#new', as: :contact_kevin
  match 'blog', to: 'articles#index', as: :blog
  match ':id', to: 'pages#show', as: :page

end

app/views/layouts/structure/_disqus-comment-count.html.erb
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'kevinjstone'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

app/views/layouts/structure/_disqus-thread.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'kevinjstone'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/structure/_facebook-scripts.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/structure/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-9">
      <p>&copy;<%= Time.now.year %> <%= @site_title if @site_title %></p>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-3">
      <p class="pull-right">Developed by <%= link_to 'Stizelwebs.com', 'http://www.stizelwebs.com' %></p>
    </div>
  </div>
</footer>

app/views/layouts/structure/_jumbotron.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron content-container-margin-top">
  <div class="col-md-6 col-lg-6"></div>
  <div class="col-md-6 col-lg-6 hidden-sm hidden-xs text-right">
    <span class="kevinname"><%= @banner_name %></span>
    <p><%= @banner_content %></p>
  </div>
</div>

app/views/layouts/structure/_right-side.html.erb
<%= render 'layouts/structure/upcoming-events' %>
<%= render 'layouts/structure/side-twitter' %>

app/views/layouts/structure/_side-facebook.html.erb
<div class="fb-like-box" data-href="https://www.facebook.com/ISTAEntertainmentSpotlight" data-width="250" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>

app/views/layouts/structure/_side-twitter.html.erb
<a class="twitter-timeline"  href="https://twitter.com/ActsofKevin"  data-widget-id="442785919003660288">Tweets by @ActsofKevin</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/structure/_top-nav.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Kevin J. Stone', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class=<%= cpa(page_path('bio')) %>><%= link_to 'Bio', page_path('bio') %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Media <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class=<%= cpa(gallery_path) %>><%= link_to 'Gallery', gallery_path %></li>
            <li class=<%= cpa(videos_path) %>><%= link_to 'Videos', videos_path %></li>
          </ul>
        </li>
        <li class=<%= cpa(events_path) %>><%= link_to 'Events', events_path %></li>
        <li class=<%= cpa(page_path('radio-show')) %>><%= link_to 'Radio Show', page_path('radio-show') %></li>
        <li class=<%= cpa(blog_path) %>><%= link_to 'Blog', blog_path %></li>
        <li class=<%= cpa(page_path('contact-me')) %>><%= link_to 'Contact', page_path('contact-me') %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= @facebook_url if @facebook_url %>"><i class="fa fa-facebook"></i></a></li>
        <li><a href="<%= @twitter_url if @twitter_url %>"><i class="fa fa-twitter"></i></a></li>
        <li><a href="<%= @instagram_url if @instagram_url %>"><i class="fa fa-instagram"></i></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/structure/_upcoming-events.html.erb
<% unless @next_three_events.empty? %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Upcoming Events</h3>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% @next_three_events.each do |event| %>
          <li class="list-group-item"><%= link_to event.title.truncate(100), event %>
            <br/>
            <%= event.time.to_formatted_s(:my_format) %> </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>